repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args:
          [
            --line-length,
            "80",
            --extend-select=E,
            --extend-select=I,
            --fix,
            --exclude=*.ipynb,
          ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: []
        args: [--ignore-missing-imports]

  # Configuration bandit simplifiée - utilise la config du pyproject.toml
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["--configfile", "pyproject.toml"]
