name: Documentation

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Build documentation
        run: |
          cd docs
          uv run sphinx-build -b html . _build/html -W

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/_build/html/
